### ISSUE TITLE
Can't execute rake tasks

### ISSUE THREAD

**Issue by lucca65** [Cendrao/ruby-fizzbuzz#6]
Following the readme, I can't make it work.

```
$ rake print[10,20]   
zsh: no matches found: print[10,20]
```

```
rake fizzbuzz[10] 
zsh: no matches found: fizzbuzz[10]
```

if Ignore the docs and call the rake task properly i get the following:

```
rake fizzbuzz 10 20
rake aborted!
NoMethodError: undefined method `fizzbuzz' for main:Object
/Users/Lucca/Development/ruby/scripts/ruby-fizzbuzz/rakefile:5:in `block in <top (required)>'
Tasks: TOP => fizzbuzz
(See full trace by running task with --trace)
```

**Comment by Cendrao** [comment]
I realized that you are using zsh, please can you try to run `rake 'print[1,10]'` ? 

I know that is not a good solution yet, but I am looking for something else.

**Comment by lucca65** [comment]
Great! This works!

**Comment by Cendrao** [comment]
Update de readme with that! Thanks!

Commit 2488539
